### ISSUE TITLE
Upgrading from v.1: GAPI: Failed to authenticate user. Error: "{ "error": "invalid_grant", "error_description": "Bad Request" }

### ISSUE THREAD

**Issue by ZaneCEO** [erebusnz/gapi-google-analytics-php-interface#116]
Hi,
I'm experiencing a problem upgrading from GAPI v.1 (Google Code version) form the new v.2 (GitHub version).

Problem
-----------
```
Fatal error: Uncaught exception 'Exception' with message 'GAPI: Failed to authenticate user. Error: "{ "error": "invalid_grant", "error_description": "Bad Request" } "' in /home/Componenti/gapi-google-analytics-php-interface/gapi.class.php:624 Stack trace: #0 /home/Componenti/gapi-google-analytics-php-interface/gapi.class.php(52): gapiOAuth2->fetchToken('address@mydomain.com', '/path/to/ouauth.p12', NULL) #1 
...
```

Server
--------
* Linux CentOS release 6.6 (Final) (2.6.32-504.12.2.el6.x86_64)
* PHP 5.6.7
* Apache/2.2.15

What I did
-------------
I basically followed your instruction and changed the second parameter of the construct() form `password` to `/path/to/ouauth.p12` obtained form my just-created Google Developers project.

The `address@mydomain.com` user has `Read and Analyse` permission and I can actually use it to do the browser-login and see my stats.

[My server's clock is in sync with NTP] (https://developers.google.com/analytics/devguides/reporting/core/v2/gdataAuthentication)

Code
------
The relevant section of my code are:

```
$this->gapi=new GoogleAnalytics($mail,$p12path);
$this->gapi->requestReportData($report_id, $timegroup, array('visitors', 'pageviews', 'visits'), $timegroup, null, $this->yearStart, $this->dayToday, 1, 1000);
$dataset=$this->gapi->getResults();
```

Other
-------
With v.1 this code was working just fine.

What other datail can I provid? thanks for your help!

**Comment by ZaneCEO** [comment]
Ok, I overlooked the part where now you have to use the `xxx@developer.gserviceaccount.com` address. Fixed that, I still get

```
 'GAPI: Failed to request report data. Error: "{"error":{"errors":[{"domain":"global","reason":"insufficientPermissions","message":"User does not have any Google Analytics account."}],"code":403,"message":"User does not have any Google Analytics account."}}"
```

I have already added `xxx@developer.gserviceaccount.com` address to the admin interface.

**Comment by ZaneCEO** [comment]
Ok, I just had to wait! Problem solved! https://turbolab.it/statistiche :+1:

**Comment by erebusnz** [comment]
Great glad to hear it worked for you! :+1: Please let me know if you have any suggested improvements to the instructions. The new Google authentication scheme is quite convoluted.

**Comment by ZaneCEO** [comment]
Thanks! I re-read the doc and looks good. Nothing to add really.
