### ISSUE TITLE
Undefined index: rows

### ISSUE THREAD

**Issue by vitaha85** [erebusnz/gapi-google-analytics-php-interface#119]
when empty response

PHP notice
Undefined index: rows

...
//Load result entries
             foreach ($json['rows'] as $row) {
                 $metrics = array();
                 $dimensions = array();
...

http://prntscr.com/7bsel4

Need check
 if (isset($json['rows'])) {
  ...
}

**Comment by erebusnz** [comment]
Issue fixed in [commit 3ae92e1458fcec021fba5ea60a1f9a7bdaeb3238](https://github.com/erebusnz/gapi-google-analytics-php-interface/commit/3ae92e1458fcec021fba5ea60a1f9a7bdaeb3238) will be included in next version. Thanks
