### ISSUE TITLE
 Failed load key file key.p12

### ISSUE THREAD

**Issue by Makcym** [erebusnz/gapi-google-analytics-php-interface#120]
Hi 
I did all of the new instruction on different sites with PHP 5.3.3, 
30 second recording process http://1smorgon.by/demo/error.gif 

Fatal error: Uncaught exception 'Exception' with message 'GAPI: Failed load key file "key.p12". 
Check if correct p12 format.' in YYY.php:603 
Stack trace: 
#0 YYY.php(126): gapiOAuth2->fetchToken('XXX@developer.gserviceaccount.com', 'YYY.php', NULL) 
#1 YYY.php(788): gapi->__construct('XXX@developer.gserviceaccount.com', 'YYY.php') 
#2 {main} thrown in YYY.php on line 603

**Comment by GLStephen** [comment]
You need to have the key file in the directory with the library. You can
download the keyfile from the Google API credentials pages.

**Comment by erebusnz** [comment]
Hi @Makcym,

It seems you are doing all of the right things. I have just added an additional check for the p12 file in the [latest commit](https://github.com/erebusnz/gapi-google-analytics-php-interface/blob/1cd7667e2c03aec7b8f479e37616e9897fecf9e7/gapi.class.php).

Please can you try this and send me the results. If we can't get this to authenticate I might have to ask for a copy of your p12 file to diagnose.

**Comment by Makcym** [comment]
Thanks for the help. The new class has not solved the problem.
http://1smorgon.by/demo/demo.zip

**Comment by mujji89** [comment]
Well same error appeared for me. To solve it I gave the absolute directory path to the file. In my framework it worked like this

$ga = new gapi($GAPI['ga_account'], Yii::app()->basePath."/extensions/googleanalytics/key-file.p12");

**Comment by erebusnz** [comment]
Hi @Makcym 

Using your P12 file and user, my system was able to authenticate with Google (only error was that '471893551242-cmibkttuapqnkq5qdt4ocjln24l5laiv@developer.gserviceaccount.com' did not have Google Analytics access configured).

Please also provide a copy of the exception produced when run the code.

**Comment by Makcym** [comment]
mujji89 
That's what I was doing home /user/www/...

erebusnz
http://1smorgon.by/demo/example.report.php

Fatal error: Uncaught exception 'Exception' with message 'GAPI: Failed load key file "key.p12". Unable to load pkcs12 check if correct p12 format.' in /home/user1178311/www/1smorgon.by/demo/gapi.class.php:622 Stack trace: #0 /home/user1178311/www/1smorgon.by/demo/gapi.class.php(55): gapiOAuth2->fetchToken('471893551242-cm...', 'key.p12', NULL) #1 /home/user1178311/www/1smorgon.by/demo/example.report.php(5): gapi->__construct('471893551242-cm...', 'key.p12') #2 {main} thrown in /home/user1178311/www/1smorgon.by/demo/gapi.class.php on line 622

**Comment by erebusnz** [comment]
Hi @Makcym

Please add

error_reporting(E_ALL);
ini_set('display_errors', 1);

And then let me know if there are any warnings displayed in addition to the exception.

Would you mind emailing me (stig@sdm.co.nz) a copy of the results of the phpinfo(); method, and also a copy of your php.ini?

I would like to understand what is going wrong with your openssl_pkcs12_read method.

It is possible it has been disabled by your hosting company, or there is a bug with OpenSSL module installed
.
Cheers,
Stig

**Comment by lukyrys** [comment]
This solve my problem :) When class is loaded by sth autoloader make this problem..

```php
    if (!file_exists($key_file)) {
      if ( !file_exists(__DIR__."/".$key_file) ) {
        throw new Exception('GAPI: Failed load key file "' . $key_file . '". File could not be found.');
      } else {
        $key_file = __DIR__."/".$key_file;
      }
    }
```

**Comment by Makcym** [comment]
Hi.
On the other hosting class I worked successfully. In the instructions it is desirable to add the need to add technical mail (@ developer.gserviceaccount.com) in user analytics

**Comment by erebusnz** [comment]
Hi @Makcy,

Latest commit has a patch created by @neurofuzzy which makes fixes a bug with fopen authentication.

Please try this.

@lukyrys - Thank you for suggestion, I will review key-file loading for checking for __DIR__ location.

**Comment by lukyrys** [comment]
@erebusnz +1
