### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'GAPI: 

### ISSUE THREAD

**Issue by dawidnex** [erebusnz/gapi-google-analytics-php-interface#122]
Hi I have such a problem - with conection - can somebody help ?

:  Uncaught exception 'Exception' with message 'GAPI: Failed to authenticate user. Error: "https://developers.google.com/accounts/docs/AuthForInstalledApps
"' in /admin-user/CLASS/Managers/gapi.class.php:418
Stack trace:
#0 /admin-user/CLASS/Managers/gapi.class.php(62): gapi->authenticateUser('here is may email', 'here is may password')
#1 /admin-user/CLASS/Managers/AnalyticsManager.class.php(50): gapi->__construct('here is may email..', 'here is may password')
#2 /admin-user/dashboard.php(165): AnalyticsManager->pages('110')
#3 {main}
  thrown in

**Comment by erebusnz** [comment]
On 27th May, Google disabled all other authentication systems apart from OAuth2. This means older versions of GAPI will not function any longer.

You will need to upgrade to the latest version of GAPI Version 2.0 which you can download from this github project. Follow the instructions carefully in the Readme.MD to set up this new OAuth2 authentication, it is quite complicated.
