### ISSUE TITLE
example.account.php - Issue related to requestAccountData

### ISSUE THREAD

**Issue by sudhakar76** [erebusnz/gapi-google-analytics-php-interface#123]
Code:
```php
    $ga = new gapi("XXXXXXXX@developer.gserviceaccount.com", "key.p12");
    $ga->requestAccountData();
    foreach($ga->getResults() as $result)  {
      echo $result . ' (' . $result->getProfileId() . ")<br />";
    }
```
No longer works this way as it is described currently, because gapi::accountObjectMapper() does not store result in the local variable *results* in order to get it later using gapi::getResults() as descibed over here. Also this does not seems to work now
$result->getProfileId()

So currently we can only use something like this:
```php
    $ga = new gapi("XXXXXXXX@developer.gserviceaccount.com", "key.p12");
    $results = $ga->requestAccountData();
    foreach($results as $result)  {
      $properties =  $result->getProperties();
    }
```

**Comment by erebusnz** [comment]
Issue is fixed in latest commit 6846b0699c0e7244aab6b937ca2475eae8e64990.

Thanks!
