### ISSUE TITLE
User impersonation via $delegate_email argument without Google Apps account

### ISSUE THREAD

**Issue by jcjmcclean** [erebusnz/gapi-google-analytics-php-interface#124]
When attempting to impersonate a user using the $delegate_email argument, I get the following exception:

    GAPI: Failed to authenticate user. Error: "{
        "error": "unauthorized_client",
        "error_description": "Unauthorized client or scope in request."
    }

I have read elsewhere about needing to ['Delegate domain-wide authority to the service account'](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) using the Google Apps admin console. However we don't have Google Apps at all. Is there any way around this?

**Comment by erebusnz** [comment]
I don't believe it is possible to use delegation on a non-Google apps account (this means the feature can't be used on a Gmail).

I would like to know if anyone is able to use any kind of delegated Google API OAuth2 authentication with gmail; please update this issue if you find a way.

Cheers,
Stig
