### ISSUE TITLE
GAPI: Failed load key file

### ISSUE THREAD

**Issue by alexkleinubing** [erebusnz/gapi-google-analytics-php-interface#127]
I got a error trying get file in same directory:

```Uncaught exception 'Exception' with message 'GAPI: Failed load key file "bimboo-dev-8cec93dc7d08.p12". File could not be found.' in /var/www/bimboo/components/analyticsgraph/gapi.class.php:610 Stack trace: #0 /var/www/bimboo/components/analyticsgraph/gapi.class.php(55): gapiOAuth2->fetchToken('0123456789-kk...', 'bimboo-dev-8cec...', NULL) #1 /var/www/bimboo/components/analyticsgraph/config.php(176): gapi->__construct('0123456789-kk...', 'bimboo-dev-8cec...') #2 [internal function]: analyticsgraph->view(Array) #3 /var/www/bimboo/core/controller.php(91): call_user_func_array(Array, Array) #4 /var/www/bimboo/router.php(454): controller::dispatch_request() #5 {main} thrown```

GAPI fail to load key file :S

**Comment by Warface** [comment]
Try with the absolute path ei: /home/test/public_html/pathtothefile/key.p12

**Comment by erebusnz** [comment]
Please try version v2.0.1 which has an updated key file loading method that has an additional attempt to load from currently folder. Otherwise you can use an absolute path as suggested by @Warface.
