### ISSUE TITLE
API not working for me 

### ISSUE THREAD

**Issue by archanamapari** [erebusnz/gapi-google-analytics-php-interface#135]
Hi,

I have downloaded your code and created service account. As per suggestion I have created and downloaded .p12 file and placed same folder of gapi.clss.php. 
After that I checkedexample.report.php. that has given following error.

User does not have any Google Analytics account.

Please help me for solving this issue. First time I am integrating gapi.

Thanks,
Archana

**Comment by sankalpsans** [comment]
You'll need to add the email address to your GA property from the "Admin" section of GA. This is the email address which you'll receive from Google Dev Console, and will look something like XXXXXXXX@developer.gserviceaccount.com

**Comment by archanamapari** [comment]
Yes, I got that and implemented it. Now It is working fine.

Anyway thanks for your reply.
