### ISSUE TITLE
Filter by Property

### ISSUE THREAD

**Issue by webplease** [erebusnz/gapi-google-analytics-php-interface#136]
Hi,

i have more Web Property (web sites) under my Account ID ... how can i switch between this ?

**Comment by sankalpsans** [comment]
Define a configuration which switches between relevant emails and credentials. This is something to be implemented at your end, not an "issue" with this codebase.

**Comment by erebusnz** [comment]
I suggest using the GA profile ID to switch between web properties assuming your analytics profiles are set up this way.
