### ISSUE TITLE
Getting the following error for the gapi class. Please help me out

### ISSUE THREAD

**Issue by qabispl** [erebusnz/gapi-google-analytics-php-interface#138]
Getting the following error for the gapi class. Please help me out
Fatal error: Uncaught exception 'Exception' with message 'GAPI: Failed to authenticate user. Error: "{ "error": "invalid_grant", "error_description": "Bad Request" } "' in /var/www/vhosts/.org/httpdocs/modules/ganalyticsnew/gapi.class.php:662 Stack trace: #0 /var/www/vhosts/.org/httpdocs/modules/ganalyticsnew/gapi.class.php(54): gapiOAuth2->fetchToken('230397972383-gp...', 'APIProject-6f76...', NULL) #1 /var/www/vhosts/.org/httpdocs/modules/ganalyticsnew/analytics.filter.php(15): gapi->__construct('230397972383-gp...', 'APIProject-6f76...') #2 {main} thrown in /var/www/vhosts/.org/httpdocs/modules/ganalyticsnew/gapi.class.php on line 662

Note - Procedure mentioned in this thread of stackoverflow is done - http://stackoverflow.com/questions/30477341/gapi-is-shutting-down-need-a-lightweight-php-api-for-google-analytics/

**Comment by sankalpsans** [comment]
Check the time and time zone on the machine you're making request from.

**Comment by qabispl** [comment]
Thank you for your reply. I have checked the time and timezone of the Machine, It shows Europe/London timezone. How it will be a issue for not displaying the result? How to solve this? Do I need to check any other timezone? Please reply about the same.

**Comment by sankalpsans** [comment]
Hey, just correct this time. I recommend you use something like this [https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-12-04] to do it. This should enable you to use this.

**Comment by danielevian** [comment]
Hi - I'm in the same situation, but syncing the time didn't help.
I have created the service account, used that corresponding email address + p12 key file, but it gives back an invalid_grant as well. Any other ideas? Thanks

**Comment by sankalpsans** [comment]
Hey, do one thing. Checkout the same code on your local machine, or some other machine, and run the code. This way you can narrow down if it an environment-specific error (which I think it might very well be).

**Comment by qabispl** [comment]
Any other solution for this. Please share.

**Comment by danielevian** [comment]
Hi - tried in localhost, everything isolated, just your lib + a 2 lines script, ntpdate synced, new service credentials (just to be sure), nothing changed.
Just when I create gapi instance, it gives back the invalid_grant. The thing that makes it very suspicious to me is that I can change the email that I pass to the gapi constructor as I want, but the error is the same. If you have any insight that would be appreciated...

**Comment by qabispl** [comment]
Working fine after setting up server time. Thanks for the help 'sankalpsans'

**Comment by sankalpsans** [comment]
You're welcome! I guess you can mark the issue as closed now. :smile_cat:

**Comment by qabispl** [comment]
Closed the topic. Thank you.
