### ISSUE TITLE
Google account limit

### ISSUE THREAD

**Issue by alexkleinubing** [erebusnz/gapi-google-analytics-php-interface#141]
Hello, this isnt a true issue, but a question...
I created a project in my system to display the reports from Google Analytics.
Use an email "@gserviceaccount" and a key p12.
The e-mail "master" was added to the analytics of accounts for each client, but we reached the limit of accounts to display. Is there any known alternative?
i dont want create a project to each cliente analytics and take each p12 key. =/

**Comment by erebusnz** [comment]
Hi Alex,

Can you explain what you mean by 'we reached the limit of accounts to display'?

Cheers,
Stig
