### ISSUE TITLE
getUpdated 

### ISSUE THREAD

**Issue by joankent** [erebusnz/gapi-google-analytics-php-interface#143]
Fatal error: Uncaught exception 'Exception' with message 'No valid root parameter or aggregate metric called "Updated"' 

I have this message in example.filter.php file because the getUpdated function is not in the file, do you have this function? or can explain me how I can do this please?

**Comment by erebusnz** [comment]
Thanks, latest commit includes fix as getUpdated is no longer available in the V3 of the Google Analytics API.

This is because I understand that analytics data is now up to date at the time it is requested, rather than the earlier caching model where 'updated' was relevant.
