### ISSUE TITLE
ga_profile_id, gapi("XXXXXXXX

### ISSUE THREAD

**Issue by m1chae11** [erebusnz/gapi-google-analytics-php-interface#146]
Hi there can you tell me what is the ga_profile_id and gapi("XXXXXXXX

define('ga_profile_id','your profile id');
$ga = new gapi("XXXXXXXX@developer.gserviceaccount.com", "key.p12");

where do i get this information?
Thanks
Michael

**Comment by ferozsho** [comment]
@m1chae11 
Hi, 
Google Analytics :: Administration > Reporting View Settings > [View Settings] 
use **View ID**
![your-profile-id](https://cloud.githubusercontent.com/assets/4263848/12989245/9e0c252a-d12a-11e5-937c-5934ccee58ed.jpg)
