### ISSUE TITLE
Invalid JWT ?

### ISSUE THREAD

**Issue by yeremi** [erebusnz/gapi-google-analytics-php-interface#147]
GAPI: Failed to authenticate user. Error: "{
 "error": "invalid_grant",
 "error_description": "Invalid JWT: Token must be a short-lived token and in a reasonable timeframe"
}

**Comment by DanRobinsonRV** [comment]
I'm also getting JWT errors, though my error_description is "Invalid JWT Signature." Could this be the same issue?

**Comment by digger5212** [comment]
I'm also getting JWT errors, though my error_description is "Invalid JWT Signature."  Can you help me?

**Comment by erebusnz** [comment]
I haven't been able to replicate this issue, but it would certainly be caused if your server time was out (>12 hours).

If your server time is accurate (suggest installing/running NTPd) please add the following after line #660

var_dump($post_variables, $response);

Then post the response back on this issue so I can investigate further.

Cheers,
Stig

**Comment by Gallaecio** [comment]
I just got "Invalid JWT Signature.". The issue was that I was using an email account in my script that did not match the .p12 file (I had updated the p12 file but forgot to update the email address). I hope it helps if someone else ends up here in the future.

**Comment by flastowizka** [comment]
@Gallaecio this works for me. thanks
