### ISSUE TITLE
User does not have permissions 

### ISSUE THREAD

**Issue by soySantosPerez** [erebusnz/gapi-google-analytics-php-interface#156]
I just do all the steps and the code show me:

Fatal error: Uncaught Exception: GAPI: Failed to request report data. Error: "User does not have sufficient permissions for this profile." in /..../gapi.class.php:208 Stack trace: #0 /..../index.php(7): gapi->requestReportData(145141242, Array, Array) #1 {main} thrown in /...../gapi.class.php on line 208

I just added the account to my Google Analytics

**Comment by kimboender** [comment]
Having the same problem here, did you fix it evetually? I would love to have the answer to this problem.

**Comment by soySantosPerez** [comment]
Yes @kimboender, you need to have your profile id:
`define('ga_profile_id','222216518');`
Then call gapi class:
`$ga = new gapi("console@mail.com", "file.p12");`
Then make the query:
`$ga->requestReportData(ga_profile_id,array('day'),array('pageviews','visits', 'users', 'sessions', 'bounceRate'),'day',$filter, date("Y-m").'-01');`
Finally:
`print $ga->getResults();`

**Comment by kimboender** [comment]
Thank you ery much for answering this question, but where can i find this profile id. According to some people i can find this in the URL when i go to the project in the google-analytics-site. This does not seem to work.. Also i can't find it in the APi-console. Can you maybe point me in the right direction?

Tahnks in advance!

**Comment by soySantosPerez** [comment]
Whit this:

```
<?php

require 'gapi.class.php';

$ga = new gapi("XXXXXXXX@developer.gserviceaccount.com", "key.p12");

$ga->requestAccountData();

foreach($ga->getAccounts() as $result)

{

  echo $result . ' ' . $result->getId() . ' (' . $result->getProfileId() . ")<br />";

}
```

you can get de profile id of the account and then, you can use it ;)

If you resolved you'r problem, please, tell me ;)

**Comment by erebusnz** [comment]
Please check you have the correct profile ID, use code from @LOverride to list profile IDs as explained above.
